DROP TRIGGER IF EXISTS check_release_date_on_insert ON Releases;
DROP TRIGGER IF EXISTS check_release_date_on_update ON Releases;
DROP TRIGGER IF EXISTS check_sprint_dates_on_update ON Sprint;

DROP FUNCTION IF EXISTS get_sprints_by_year_and_team;
DROP FUNCTION IF EXISTS get_top_10_task_risks;
DROP FUNCTION IF EXISTS calculate_team_load;
DROP FUNCTION IF EXISTS get_story_points_per_user_in_sprint;
DROP FUNCTION IF EXISTS check_release_date;
DROP FUNCTION IF EXISTS check_sprint_dates_for_releases;
DROP PROCEDURE IF EXISTS process_idea;

ALTER TABLE Sprint DROP CONSTRAINT IF EXISTS sprint_dates_check;
ALTER TABLE Task DROP CONSTRAINT IF EXISTS story_points_nonnegative;
ALTER TABLE Risk DROP CONSTRAINT IF EXISTS probability_valid_range;
ALTER TABLE Risk DROP CONSTRAINT IF EXISTS estimated_loss_nonnegative;

ALTER TABLE Task_Tag DROP CONSTRAINT IF EXISTS task_tag_pkey;
ALTER TABLE Idea_Risk DROP CONSTRAINT IF EXISTS idea_risk_pkey;
ALTER TABLE Task_Risk DROP CONSTRAINT IF EXISTS task_risk_pkey;
ALTER TABLE Role_Status DROP CONSTRAINT IF EXISTS role_status_pkey;

DROP TABLE IF EXISTS Task_Tag CASCADE;
DROP TABLE IF EXISTS Idea_Risk CASCADE;
DROP TABLE IF EXISTS Task_Risk CASCADE;
DROP TABLE IF EXISTS Role_Status CASCADE;

DROP TABLE IF EXISTS Tag CASCADE;
DROP TABLE IF EXISTS Risk CASCADE;
DROP TABLE IF EXISTS Releases CASCADE;
DROP TABLE IF EXISTS Idea CASCADE;
DROP TABLE IF EXISTS Task CASCADE;
DROP TABLE IF EXISTS Sprint CASCADE;
DROP TABLE IF EXISTS Status CASCADE;
DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Team CASCADE;
DROP TABLE IF EXISTS Role CASCADE;
